name: flutter_test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.1.0'
      - run: flutter pub get
      - run: flutter test