name: flutter_test

on:
  push:
  workflow_dispatch:

jobs:
  unit_and_widget_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
  
  integration_test_iOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: futureware-tech/simulator-action@v1
        with: 
          model: 'iPhone 8'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'
      - name: "Run Flutter Integration tests"
        run: "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart"

  integration_test_Android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'
      - name: boot Android Emulator And Run Flutter Integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart"

  integration_test_web_mac:
    runs-on: macos-latest
    strategy:
      matrix:
        browser: [chrome, safari, firefox]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'
      - run: flutter config --enable-web
      - name: boot chromedriver
        if: matrix.browser == 'chrome'
        run: chromedriver --port=4444 &
      - name: boot safaridriver
        if: matrix.browser == 'safari'
        run: safaridriver --port=4444 &
      - name: boot msedgedriver
        if: matrix.browser == 'edge'
        run: msedgedriver --port=4444 &
      - name: boot geckodriver
        if: matrix.browser == 'firefox'
        run: geckodriver --port=4444 &
      - run: sleep 5
      - name: Run Flutter Integration tests
        run: "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --profile --browser-name=${{ matrix.browser }}"

  integration_test_web_win_edge:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          # flutter-version: '2.2.0'
          channel: 'master'
      - run: flutter config --enable-web
      - name: boot msedgedriver
        run: Start-Process -FilePath msedgedriver -ArgumentList "--port=4444"
      - run: sleep 5
      - name: Run Flutter Integration tests
        run: "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --profile --browser-name=edge"

  integration_test_web_win_firefox:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'
      - run: flutter config --enable-web
      - name: boot geckodriver
        run: Start-Process -FilePath geckodriver
      - run: sleep 5
      - name: Run Flutter Integration tests
        run: "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --profile --browser-name=firefox"