name: flutter_test

on:
  push:
  workflow_dispatch:

jobs:
  unit_and_widget_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
  
  integration_test_iOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: futureware-tech/simulator-action@v1
        with: 
          model: 'iPhone 8'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'
      - name: "Run Flutter Integration tests"
        run: "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart"

  integration_test_Android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'
      - name: boot Android Emulator And Run Flutter Integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart"

  integration_test_chrome:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'
      - run: flutter config --enable-web
      - uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: '91.0.4472.19'
      - name: boot chromedriver
        run: chromedriver --port=4444
      - run: sleep 5
      - name: Run Flutter Integration tests
        run: "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server"